[SDSF_SETTINGS]
sdsf = T:\work\giss\monthly\202603mar\gallaga\LND_PPLC_xxx_applications\Create new feature class LND_PPLC_ planning_applications.xlsx
sheet_name = "DATASET DETAILS"
SDSF_IGNORE_FIELDS = ["OBJECTID", "GLOBALID", "SHAPE", "SHAPE_AREA", "SHAPE_LENGTH"]

[FEATURE_SETTINGS]
add_editor_tracking = False
EDIT_PERMISSIONS_USERS = []

ready_to_add_to_replica = False
replica_name = LND_Rosde

subtypes = False
topology_dataset = False
subtype_field =
subtype_domains = {}

unique_id_fields = [{}]

[NEW_DOMAIN_TYPES]
# You can uncomment and define these as needed
;LND_fac_snow_contract_asset = TEXT
;LND_fac_snow_contract_group = SHORT
;LND_fac_snow_group_type = TEXT
;LND_fac_snow_vendor = SHORT
