[GEOLOCATE]
# Data warehouse source tables and target SDE features
# Each entry: [dw_table_name, target_sde_feature_name]
dw_source_tables = [["OPENDATA_SOURCE.PPLC_PLANNING_APPLICATIONS", "SDEADM.LND_PPLC_planning_applications"], ["OPENDATA_SOURCE.PPLC_SUBDIVISION_APPLICATIONS", "SDEADM.LND_PPLC_subdivision_applications"]]
pid_field = PID
truncate_and_load = True
