[SDSF_SETTINGS]
sdsf = T:\work\giss\monthly\202506june\gallaga\LND_floodplain_overlay\scripts\DSF_LND_floodplain_overlay.xlsx
sheet_name = "DATASET DETAILS"
SDSF_IGNORE_FIELDS = ["OBJECTID", "GLOBALID", "SHAPE", "SHAPE_AREA", "SHAPE_LENGTH"]

[FEATURE_SETTINGS]
add_editor_tracking = True
EDIT_PERMISSIONS_USERS = ["HRM\\GIS_ZONE_EDITOR",]

ready_to_add_to_replica = True
replica_name = LND_Rosde

subtypes = False
topology_dataset = False
subtype_field = 
subtype_domains = {}

[UNIQUE_ID_FIELDS]
; TRN_park_and_ride = [{"field": "PNRID", "prefix": "PNR"}]
TRN_park_and_ride = [{}]

[NEW_DOMAIN_TYPES]
# You can uncomment and define these as needed
# TRN_curbuse_type = TEXT
# TRN_curb_qualifier = SHORT
LND_floodplain_overlay_code = TEXT
LND_bylaw_code = TEXT
